apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "simpleapi.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "simpleapi.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "simpleapi.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "simpleapi.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.targetPort }}
          name: http
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: {{ .Values.env.aspnetcoreEnvironment | quote }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        livenessProbe:
          {{- toYaml .Values.livenessProbe | nindent 10 }}
        readinessProbe:
          {{- toYaml .Values.readinessProbe | nindent 10 }}
