apiVersion: v1
kind: Service
metadata:
  name: {{ include "simpleapi.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "simpleapi.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "simpleapi.selectorLabels" . | nindent 4 }}
  ports:
  - name: http
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
    {{- if eq .Values.service.type "NodePort" }}
    nodePort: {{ .Values.service.nodePort }}
    {{- end }}
    protocol: {{ .Values.service.protocol }}
